export const CATEGORIES = [
  {
    id: 'butter-cookies',
    name: 'Butter Cookies',
    emoji: '🍪',
    itemCount: 12,
    parentCategory: 'Cookies',
  },
  {
    id: 'dry-fruit-cookies',
    name: 'Dry Fruit Cookies',
    emoji: '🥜',
    itemCount: 8,
    parentCategory: 'Cookies',
  },
  {
    id: 'almond-crunch',
    name: 'Almond Crunch',
    emoji: '🌰',
    itemCount: 6,
    parentCategory: 'Cookies',
  },
  {
    id: 'choco-lava-bites',
    name: 'Choco Lava Bites',
    emoji: '🌋',
    itemCount: 10,
    parentCategory: 'Cookies',
  },
  {
    id: 'oatmeal-cookies',
    name: 'Oatmeal Cookies',
    emoji: '🌾',
    itemCount: 7,
    parentCategory: 'Cookies',
  },
  {
    id: 'tutti-frutti-cupcake',
    name: 'Tutti Frutti Cupcake',
    emoji: '🌈',
    itemCount: 9,
    parentCategory: 'Cupcakes',
  },
  {
    id: 'vanilla-cupcake',
    name: 'Vanilla Cupcake',
    emoji: '🥧',
    itemCount: 11,
    parentCategory: 'Cupcakes',
  },
  {
    id: 'almond-cupcake',
    name: 'Almond Cupcake',
    emoji: '☕',
    itemCount: 8,
    parentCategory: 'Cupcakes',
  },
  {
    id: 'chocolate-cupcake',
    name: 'Chocolate Cupcake',
    emoji: '🍫',
    itemCount: 13,
    parentCategory: 'Cupcakes',
  },
  {
    id: 'wheat-brownies',
    name: 'Wheat Brownies',
    emoji: '🌾',
    itemCount: 6,
    parentCategory: 'Brownies',
  },
  {
    id: 'fudgy-chocolate-brownies',
    name: 'Fudgy Chocolate Brownies',
    emoji: '🍬',
    itemCount: 10,
    parentCategory: 'Brownies',
  },
  {
    id: 'brownie-cookie-bars',
    name: 'Brownie Cookie Bars',
    emoji: '🍫',
    itemCount: 7,
    parentCategory: 'Brownies',
  },
];

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Classic Chocolate Chip Cookies',
    category: 'Cookies',
    price: 180,
    old_price: 220,
    rating: 4.8,
    review_count: 156,
    bakery_name: 'Sweet Delights Bakery',
    delivery_time: '25-30 mins',
    image_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400&h=300&fit=crop&crop=center',
    description: 'Freshly baked chocolate chip cookies with premium Belgian chocolate chunks. Made with real butter and love.',
    ingredients: ['Flour', 'Butter', 'Brown Sugar', 'Chocolate Chips', 'Vanilla', 'Eggs'],
    is_trending: true,
    discount_percent: 18,
  },
  {
    id: '2',
    name: 'Red Velvet Cupcakes',
    category: 'Cupcakes',
    price: 120,
    rating: 4.9,
    review_count: 203,
    bakery_name: 'Cake Heaven',
    delivery_time: '20-25 mins',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop&crop=center',
    description: 'Moist red velvet cupcakes topped with creamy cream cheese frosting. A classic favorite.',
    ingredients: ['Flour', 'Cocoa Powder', 'Red Food Coloring', 'Cream Cheese', 'Butter', 'Sugar'],
    is_trending: true,
    discount_percent: 0,
  },
  {
    id: '3',
    name: 'Fudgy Chocolate Brownies',
    category: 'Brownies',
    price: 250,
    old_price: 300,
    rating: 4.7,
    review_count: 89,
    bakery_name: 'Brownie Bliss',
    delivery_time: '30-35 mins',
    image_url: 'https://images.unsplash.com/photo-1607478900766-efe13248b125?w=400&h=300&fit=crop&crop=center',
    description: 'Rich, fudgy brownies with walnuts. Perfect balance of chewy and chocolatey goodness.',
    ingredients: ['Dark Chocolate', 'Butter', 'Sugar', 'Eggs', 'Flour', 'Walnuts'],
    is_trending: false,
    discount_percent: 17,
  },
  {
    id: '4',
    name: 'Almond Butter Cookies',
    category: 'Cookies',
    price: 160,
    rating: 4.6,
    review_count: 124,
    bakery_name: 'Nutty Delights',
    delivery_time: '25-30 mins',
    image_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=300&fit=crop&crop=center',
    description: 'Crunchy almond cookies made with real almond butter. Perfect for almond lovers.',
    ingredients: ['Almond Flour', 'Almond Butter', 'Honey', 'Vanilla', 'Sea Salt'],
    is_trending: true,
    discount_percent: 0,
  },
  {
    id: '5',
    name: 'Vanilla Bean Cupcakes',
    category: 'Cupcakes',
    price: 110,
    rating: 4.8,
    review_count: 178,
    bakery_name: 'Cake Heaven',
    delivery_time: '20-25 mins',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop&crop=center',
    description: 'Light and fluffy vanilla cupcakes with Madagascar vanilla beans and buttercream frosting.',
    ingredients: ['Flour', 'Butter', 'Sugar', 'Vanilla Beans', 'Eggs', 'Milk'],
    is_trending: false,
    discount_percent: 0,
  },
  {
    id: '6',
    name: 'Walnut Brownie Bars',
    category: 'Brownies',
    price: 280,
    old_price: 320,
    rating: 4.9,
    review_count: 67,
    bakery_name: 'Brownie Bliss',
    delivery_time: '30-35 mins',
    image_url: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop&crop=center',
    description: 'Chewy brownie bars loaded with premium walnuts. Cut into perfect squares for sharing.',
    ingredients: ['Dark Chocolate', 'Butter', 'Brown Sugar', 'Walnuts', 'Vanilla', 'Sea Salt'],
    is_trending: true,
    discount_percent: 13,
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'The chocolate chip cookies are absolutely divine! Fresh, warm, and delivered right on time. Will definitely order again!',
    date: '2024-01-15',
  },
  {
    id: '2',
    name: 'Rahul Kumar',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    rating: 5,
    comment: 'Cake Heaven never disappoints! Their red velvet cupcakes are moist, flavorful, and the cream cheese frosting is perfect.',
    date: '2024-01-12',
  },
  {
    id: '3',
    name: 'Anjali Patel',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    rating: 4,
    comment: 'Love the variety of brownies! The fudgy chocolate ones are my favorite. Packaging is excellent too.',
    date: '2024-01-10',
  },
];

export const BAKERIES = [
  {
    id: '1',
    name: 'Sweet Delights Bakery',
    rating: 4.8,
    review_count: 234,
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&h=200&fit=crop&crop=center',
    specialties: ['Cookies', 'Pastries'],
    delivery_time: '20-30 mins',
    location: 'Connaught Place, Delhi',
  },
  {
    id: '2',
    name: 'Cake Heaven',
    rating: 4.9,
    review_count: 456,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=300&h=200&fit=crop&crop=center',
    specialties: ['Cupcakes', 'Cakes'],
    delivery_time: '15-25 mins',
    location: 'Khan Market, Delhi',
  },
  {
    id: '3',
    name: 'Brownie Bliss',
    rating: 4.7,
    review_count: 189,
    image: 'https://images.unsplash.com/photo-1607478900766-efe13248b125?w=300&h=200&fit=crop&crop=center',
    specialties: ['Brownies', 'Bars'],
    delivery_time: '25-35 mins',
    location: 'Lajpat Nagar, Delhi',
  },
];