// ──────────────────────────────────────────────────────────────────────────────
// Bite Bills — Product Catalog (Deduplicated, v2)
// All products: Cookies · Cupcakes · Brownies · Toppings
// ──────────────────────────────────────────────────────────────────────────────

export const mockProducts = [

  // ── COOKIES ──────────────────────────────────────────────────────────────────

  {
    id: 'cookie-1',
    slug: 'choco-brownie-cookies',
    name: 'Choco Brownie Cookies',
    category: 'cookies',
    base_price: 439,
    is_available: true,
    is_bestseller: true,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'bestseller'],
    variants: [
      { size: '6 Cookies', price: 439 },
      { size: '12 Cookies', price: 799 },
      { size: '24 Cookies', price: 1499 },
    ],
    images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80'],
    description: 'Rich, fudgy brownie-style cookies with dark chocolate chunks. Crispy outside, molten inside.',
    ingredients: ['Dark Chocolate', 'Cocoa Powder', 'Butter', 'Brown Sugar', 'Flour', 'Vanilla'],
  },
  {
    id: 'cookie-2',
    slug: 'dry-fruit-cookies',
    name: 'Dry Fruit Cookies',
    category: 'cookies',
    base_price: 399,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'healthy'],
    variants: [
      { size: '6 Cookies', price: 399 },
      { size: '12 Cookies', price: 729 },
    ],
    images: ['https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?w=600&q=80'],
    description: 'Crunchy cookies loaded with a generous mix of cashews, almonds, pistachios and raisins.',
    ingredients: ['Cashews', 'Almonds', 'Pistachios', 'Raisins', 'Butter', 'Brown Sugar', 'Flour'],
  },
  {
    id: 'cookie-3',
    slug: 'almond-crunch',
    name: 'Almond Crunch',
    category: 'cookies',
    base_price: 379,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg'],
    variants: [
      { size: '6 Cookies', price: 379 },
      { size: '12 Cookies', price: 699 },
    ],
    images: ['https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=600&q=80'],
    description: 'Crispy almond-topped butter cookies with a satisfying crunch in every bite.',
    ingredients: ['Blanched Almonds', 'Almond Extract', 'Butter', 'Sugar', 'Flour'],
  },
  {
    id: 'cookie-4',
    slug: 'choco-lava-bites',
    name: 'Choco Lava Bites',
    category: 'cookies',
    base_price: 529,
    is_available: true,
    is_bestseller: true,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'indulgent'],
    variants: [
      { size: '6 Cookies', price: 529 },
      { size: '12 Cookies', price: 959 },
    ],
    images: ['https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=600&q=80'],
    description: 'Soft cookies with a molten dark chocolate center that oozes with every bite.',
    ingredients: ['Dark Chocolate', 'Cocoa', 'Butter', 'Brown Sugar', 'Flour', 'Vanilla'],
  },
  {
    id: 'cookie-5',
    slug: 'oatmeal-cookies',
    name: 'Oatmeal Cookies',
    category: 'cookies',
    base_price: 319,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'healthy'],
    variants: [
      { size: '6 Cookies', price: 319 },
      { size: '12 Cookies', price: 579 },
    ],
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'],
    description: 'Wholesome rolled oats with sun-dried raisins and a touch of honey.',
    ingredients: ['Rolled Oats', 'Raisins', 'Honey', 'Cinnamon', 'Butter', 'Brown Sugar'],
  },
  {
    id: 'cookie-6',
    slug: 'classic-butter-cookies',
    name: 'Classic Butter Cookies',
    category: 'cookies',
    base_price: 349,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg'],
    variants: [
      { size: '6 Cookies', price: 349 },
      { size: '12 Cookies', price: 629 },
    ],
    images: ['https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=600&q=80'],
    description: 'Melt-in-your-mouth classic butter cookies dusted with powdered sugar.',
    ingredients: ['Butter', 'Powdered Sugar', 'Flour', 'Vanilla Extract'],
  },

  // ── CUPCAKES ──────────────────────────────────────────────────────────────────

  {
    id: 'cupcake-1',
    slug: 'tutti-frutti-cupcake',
    name: 'Tutti Frutti Cupcake',
    category: 'cupcakes',
    base_price: 129,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'fruity'],
    variants: [
      { size: '1 Cupcake', price: 129 },
      { size: '6 Cupcakes', price: 699 },
    ],
    images: ['https://images.unsplash.com/photo-1587668178277-295251f900ce?w=600&q=80'],
    description: 'Colourful fruit-filled vanilla cupcake bursting with tutti frutti bits and cream frosting.',
    ingredients: ['Flour', 'Butter', 'Vanilla', 'Sugar', 'Milk', 'Tutti Frutti'],
  },
  {
    id: 'cupcake-2',
    slug: 'vanilla-cupcake',
    name: 'Vanilla Cup Cake',
    category: 'cupcakes',
    base_price: 149,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'classic'],
    variants: [
      { size: '1 Cupcake', price: 149 },
      { size: '6 Cupcakes', price: 799 },
    ],
    images: ['https://images.unsplash.com/photo-1468359601543-843bfaef291a?w=600&q=80'],
    description: 'Classic soft vanilla cupcake with whipped vanilla buttercream on top.',
    ingredients: ['Flour', 'Butter', 'Vanilla Extract', 'Sugar', 'Milk', 'Baking Powder'],
  },
  {
    id: 'cupcake-3',
    slug: 'almond-cupcake',
    name: 'Almond Cup Cake',
    category: 'cupcakes',
    base_price: 169,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'nutty'],
    variants: [
      { size: '1 Cupcake', price: 169 },
      { size: '6 Cupcakes', price: 899 },
    ],
    images: ['https://images.unsplash.com/photo-1551106652-a5bcf4b29ab6?w=600&q=80'],
    description: 'Moist almond-flavoured cupcake topped with crushed almond flakes and buttercream.',
    ingredients: ['Flour', 'Almond Extract', 'Butter', 'Sugar', 'Almonds', 'Cream'],
  },
  {
    id: 'cupcake-4',
    slug: 'chocolate-cupcake',
    name: 'Chocolate Cup Cake',
    category: 'cupcakes',
    base_price: 159,
    is_available: true,
    is_bestseller: true,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'bestseller', 'chocolate'],
    variants: [
      { size: '1 Cupcake', price: 159 },
      { size: '6 Cupcakes', price: 849 },
    ],
    images: ['https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&q=80'],
    description: 'Rich dark chocolate cupcake with silky ganache top and chocolate curls.',
    ingredients: ['Flour', 'Cocoa Powder', 'Butter', 'Dark Chocolate', 'Sugar', 'Cream'],
  },

  // ── BROWNIES ──────────────────────────────────────────────────────────────────

  {
    id: 'brownie-1',
    slug: 'fudgy-chocolate-brownies',
    name: 'Fudgy Chocolate Brownies',
    category: 'brownies',
    base_price: 319,
    is_available: true,
    is_bestseller: true,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'bestseller', 'chocolate'],
    variants: [
      { size: 'Small Box (4 pcs)', price: 319 },
      { size: 'Large Box (8 pcs)', price: 599 },
    ],
    images: ['https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=600&q=80'],
    description: 'Dense, gooey, ultra-fudgy chocolate brownie. Dark chocolate crust, chewy center.',
    ingredients: ['Dark Chocolate', 'Cocoa Powder', 'Butter', 'Brown Sugar', 'Flour', 'Vanilla'],
  },
  {
    id: 'brownie-2',
    slug: 'wheat-brownies',
    name: 'Wheat Brownies',
    category: 'brownies',
    base_price: 289,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'healthy', 'whole-wheat'],
    variants: [
      { size: 'Small Box (4 pcs)', price: 289 },
      { size: 'Large Box (8 pcs)', price: 549 },
    ],
    images: ['https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&q=80'],
    description: 'Healthy whole wheat dark chocolate brownie — guilt-free indulgence with all the richness.',
    ingredients: ['Whole Wheat Flour', 'Dark Chocolate', 'Coconut Oil', 'Brown Sugar', 'Cocoa'],
  },
  {
    id: 'brownie-3',
    slug: 'brownie-cookie-bars',
    name: 'Brownie Cookie Bars',
    category: 'brownies',
    base_price: 359,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'fusion'],
    variants: [
      { size: 'Small Box (4 pcs)', price: 359 },
      { size: 'Large Box (8 pcs)', price: 659 },
    ],
    images: ['https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80'],
    description: 'Half brownie, half cookie — the best of both worlds baked in one perfect bar.',
    ingredients: ['Dark Chocolate', 'Butter', 'Brown Sugar', 'Flour', 'Chocolate Chips', 'Vanilla'],
  },

  // ── TOPPINGS / ADD-ONS ────────────────────────────────────────────────────────

  {
    id: 'topping-1',
    slug: 'mixed-dry-fruits',
    name: 'Mixed Dry Fruits',
    category: 'toppings',
    base_price: 149,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'topping', 'add-on'],
    variants: [
      { size: '50g Pack', price: 149 },
      { size: '100g Pack', price: 269 },
    ],
    images: ['https://images.unsplash.com/photo-1597733336794-12d05021d510?w=600&q=80'],
    description: 'Premium mix of cashews, almonds, raisins and pistachios — perfect topping or snack.',
    ingredients: ['Cashews', 'Almonds', 'Raisins', 'Pistachios'],
  },
  {
    id: 'topping-2',
    slug: 'almond-flakes',
    name: 'Almond Flakes',
    category: 'toppings',
    base_price: 99,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'topping'],
    variants: [
      { size: '30g Pack', price: 99 },
      { size: '60g Pack', price: 179 },
    ],
    images: ['https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&q=80'],
    description: 'Premium toasted sliced almonds — adds crunch and elegance to any baked treat.',
    ingredients: ['Blanched Almonds'],
  },
  {
    id: 'topping-3',
    slug: 'dark-chocolate-chips',
    name: 'Dark Chocolate Chips',
    category: 'toppings',
    base_price: 119,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'topping', 'chocolate'],
    variants: [
      { size: '50g Pack', price: 119 },
      { size: '100g Pack', price: 219 },
    ],
    images: ['https://images.unsplash.com/photo-1511381939415-e44015466834?w=600&q=80'],
    description: 'Belgian dark chocolate chips — rich, intense flavour perfect for baking or topping.',
    ingredients: ['Belgian Dark Chocolate (70% Cocoa)'],
  },
  {
    id: 'topping-4',
    slug: 'white-chocolate-drizzle',
    name: 'White Chocolate Drizzle',
    category: 'toppings',
    base_price: 89,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'topping', 'chocolate'],
    variants: [
      { size: '30ml Bottle', price: 89 },
    ],
    images: ['https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=600&q=80'],
    description: 'Sweet white chocolate drizzle sauce — the perfect finishing touch for desserts.',
    ingredients: ['White Chocolate', 'Cream', 'Vanilla'],
  },
  {
    id: 'topping-5',
    slug: 'caramel-sauce',
    name: 'Caramel Sauce',
    category: 'toppings',
    base_price: 109,
    is_available: true,
    is_bestseller: false,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'topping', 'caramel'],
    variants: [
      { size: '30ml Bottle', price: 109 },
    ],
    images: ['https://images.unsplash.com/photo-1607920592519-bab2a80a4b37?w=600&q=80'],
    description: 'Homemade golden caramel drizzle made with real butter and cream — irresistible.',
    ingredients: ['Sugar', 'Butter', 'Cream', 'Vanilla', 'Sea Salt'],
  },

  // ── GIFTS ─────────────────────────────────────────────────────────────────────

  {
    id: 'gift-1',
    slug: 'assorted-gift-box',
    name: 'Assorted Gift Box',
    category: 'gifts',
    base_price: 549,
    is_available: true,
    is_bestseller: true,
    is_eggless: true,
    tags: ['eggless', 'pure-veg', 'gift', 'bestseller'],
    variants: [
      { size: 'Standard (6 Items)', price: 549 },
      { size: 'Large (12 Items)', price: 999 },
    ],
    images: ['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80'],
    description: 'A beautiful curated gift box with our bestselling cookies, brownies and toppings.',
    ingredients: ['Assorted'],
  },
]

// ── Category map for display labels ──────────────────────────────────────────
export const CATEGORY_LABELS = {
  all: '🌟 All',
  cookies: '🍪 Cookies',
  cupcakes: '🧁 Cupcakes',
  brownies: '🍫 Brownies',
  toppings: '✨ Toppings',
  gifts: '🎁 Gift Boxes',
}

export const ALL_CATEGORIES = Object.keys(CATEGORY_LABELS)